/*CMD
  command: /success
  help: 
  need_reply: false
  auto_retry_time: 
  folder: 

  <<ANSWER

  ANSWER

  <<KEYBOARD

  KEYBOARD
  aliases: 
  group: 
CMD*/

let data = JSON.parse(content)

if(data.status==true){
  
  Api.sendPhoto({
    photo:data.data,
    caption:"*Logo Generated Success ✨️\n\nGenerated By: @"+bot.name+"*",
    parse_mode:"markdown"
  })
  
}else{
Bot.sendMessage("Internal Server Error")
}
