/*CMD
  command: /unimage
  help: 
  need_reply: false
  auto_retry_time: 
  folder: 

  <<ANSWER

  ANSWER

  <<KEYBOARD

  KEYBOARD
  aliases: 
  group: 
CMD*/

let myData;
try {
  myData = JSON.parse(content);
} catch (e) {  
  throw new Error('JSON parsing error: ' + content);
}

const imageUrls = myData.imageUrls || [];
const botName = 'kingbjssbot'; // Replace with your bot's name


imageUrls.slice(0, 9).forEach((imageUrl, index) => {
  const photo = {
    photo: imageUrl,
    caption: 'Image generated by Bot 💫'
  };

  
  Api.sendPhoto(photo);
});
